version: 2
updates:
  - package-ecosystem: "github-actions" 
    directory: "/" # Location of package manifests
    target-branch: "master"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven" 
    directory: "/" # Location of package manifests
    target-branch: "master"
    schedule:
      interval: "daily"
